### ISSUE TITLE
Error while running vagrant up

### ISSUE THREAD

**Issue by CaptainJeff** [gavinln/tensorflow-ipy#7]
When i run the command vagrant up i get an error. 

==> tensorflow-ipy: fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/pip3 install httpie", "failed": true, "msg": "\n:stderr: Traceback (most recent call last):\n  File \"/usr/bin/pip3\", line 5, in <module>\n    from pkg_resources import load_entry_point\n  File \"/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py\", line 70, in <module>\n    import packaging.version\nImportError: No module named 'packaging'\n"}
==> tensorflow-ipy: 	to retry, use: --limit @/vagrant/ansible/playbook.retry
==> tensorflow-ipy: 
==> tensorflow-ipy: PLAY RECAP *********************************************************************
==> tensorflow-ipy: localhost                  : ok=22   changed=0    unreachable=0    failed=1   
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

It says "to retry, use: --limit @/vagrant/ansible/playbook.retry" so i tried ssh-ing into vagrant and running

*sudo ansible-playbook ansible/playbook.yml*

But i receive the same error

Any thoughts?

**Comment by gavinln** [comment]
Thanks for reporting this issue. I fixed the issue by upgrading to Ubuntu 16.04 and Python 3.
